### ISSUE TITLE
[ToDo] Disponibilité Hors Ligne

### ISSUE THREAD

**Issue by alphabeat** [LokIIE/IIEns#1]
Coucou !

Je me suis pas encore penché sur le code mais ce serait cool que l'appli soit dispo hors ligne, on sait tous à quel point c'est chiant d'avoir du réseau dans l'école.
Si par exemple l'emploi du temps de la semaine est chargé automatiquement genre tous les samedis pour pouvoir le consulter sans problème toute la semaine, ça peut être cool.

Aucune idée de comment faire ça, mais si j'ai le temps j'y jetterai un oeil. En attendant si quelqu'un a une idée de comment faire ça ou peut me dire que c'est pas possible et pourquoi, NP ! ^^

Alpha

**Comment by LokIIE** [comment]
Cette fonctionnalité a été implémentée pour la version 1.4 ... sortie aujourd'hui :)
