### ISSUE TITLE
[ToDo] Notifications

### ISSUE THREAD

**Issue by alphabeat** [LokIIE/IIEns#2]
C'est peut être déjà dans les petits papiers de @LokIIE mais on sait jamais ^^ 

Pour les notifs, je sais pas si on pourrait par exemple envoyer une notif une semaine avant un partiel. Sinon notifs pour les réus d'assoces (si elles sont sur l'EdT, ce qui est rare).

J'ai pas des masses d'idées concernant le système de notifs, c'est juste que c'est cool et toutes les applis le font :P 

Alpha

**Comment by LokIIE** [comment]
Cette fonctionnalité a été implémentée pour la version 1.4 ... sortie aujourd'hui :)
L'utilisateur peut maintenant recevoir des notifications pour : 
- les anniversaires du jour (publics)
- les partiels (une semaine avant)
- les nouvelles publications de news
- les events associatifs du jour

**Comment by alphabeat** [comment]
Je reçois toutes les notifs en double, je sais pas si ça vient de mon portable ou de l'appli ^^

J'ai un Samsung Galaxy S4 Mini qui tourne sous Android 4.4.2

**Comment by LokIIE** [comment]
Yep, ca vient de l'appli ^^" Je l'avais remarqué et j'ai déjà corrigé ca, mais seulement en version dev. Je ferai la maj lorsque j'aurai terminé la nouvelle fonctionnalité de l'app : la synchronisation de l'edt avec l'agenda du téléphone :)
